// https://html.spec.whatwg.org/multipage/media.html#htmlvideoelement
[Exposed=Window]
interface HTMLVideoElement : HTMLMediaElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect] attribute unsigned long width;
    [CEReactions, Reflect] attribute unsigned long height;
    readonly attribute unsigned long videoWidth;
    readonly attribute unsigned long videoHeight;
    [CEReactions, Reflect, URL] attribute USVString poster;
    [CEReactions, Reflect=playsinline] attribute boolean playsInline;

    unsigned long requestVideoFrameCallback(VideoFrameRequestCallback callback);
    undefined cancelVideoFrameCallback(unsigned long handle);
};

callback VideoFrameRequestCallback = undefined (DOMHighResTimeStamp now, VideoFrameCallbackMetadata metadata);

dictionary VideoFrameCallbackMetadata {
    DOMHighResTimeStamp presentationTime;
    DOMHighResTimeStamp expectedDisplayTime;
    unsigned long width;
    unsigned long height;
    double mediaTime;
    unsigned long presentedFrames;
};
